name : first-pipeline
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v